# =============================================================
# Django REST Framework Imports
# =============================================================
from rest_framework import serializers

# =============================================================
# Two-Factor Authentication (2FA) Serializers
# =============================================================
# These serializers handle enabling, disabling, and setting up 2FA
# for users. They ensure:
# - Only authenticated users can enable/disable 2FA
# - Tokens are numeric 6-digit TOTP codes
# - Setup serializer returns the TOTP URI and QR code for authenticator apps
# =============================================================

# =============================================================
# Base TOTP Token Validation Mixin
# =============================================================
class TOTPTokenValidationMixin:
    """
    Mixin to validate TOTP tokens.

    Ensures tokens are:
    - Only digits
    - Exactly 6 characters long
    """

    def validate_token(self, value):
        value = value.strip()

        if not value.isdigit():
            raise serializers.ValidationError("Token must contain only digits.")

        if len(value) != 6:
            raise serializers.ValidationError("Token must be a 6-digit code.")

        return value


# =============================================================
# Enable 2FA Serializer
# =============================================================
class Enable2FASerializer(TOTPTokenValidationMixin, serializers.Serializer):
    """
    Serializer to enable 2FA for an authenticated user.

    Fields:
    - token: 6-digit TOTP token generated by an authenticator app

    Validations:
    - User must be authenticated
    - Token must be numeric and 6 digits
    """

    token = serializers.CharField(
        write_only=True,
        help_text="6-digit TOTP token generated by authenticator app",
    )

    def validate(self, attrs):
        request = self.context.get("request")
        if not request or not request.user or not request.user.is_authenticated:
            raise serializers.ValidationError("Authentication required.")
        return attrs


# =============================================================
# Disable 2FA Serializer
# =============================================================
class Disable2FASerializer(TOTPTokenValidationMixin, serializers.Serializer):
    """
    Serializer to disable 2FA for an authenticated user.

    Fields:
    - token: 6-digit TOTP token to confirm disabling 2FA

    Validations:
    - User must be authenticated
    - Token must be numeric and 6 digits
    """

    token = serializers.CharField(
        write_only=True,
        help_text="6-digit TOTP token to confirm disabling 2FA",
    )

    def validate(self, attrs):
        request = self.context.get("request")
        if not request or not request.user or not request.user.is_authenticated:
            raise serializers.ValidationError("Authentication required.")
        return attrs

# =============================================================
# Verify 2FA Serializer
# =============================================================
class Verify2FASerializer(TOTPTokenValidationMixin, serializers.Serializer):
    """
    Serializer to verify a 6-digit TOTP code.
    """

    token = serializers.CharField(
        write_only=True,
        help_text="6-digit TOTP code from authenticator app",
    )
    
