LOGIN_EMAIL_PASSWORD = "EMAIL_PASSWORD"
LOGIN_GOOGLE = "GOOGLE"
LOGIN_GITHUB = "GITHUB"

LOGIN_TYPE_CHOICES = [
    (LOGIN_EMAIL_PASSWORD, "Email & Password"),
    (LOGIN_GOOGLE, "Google"),
    (LOGIN_GITHUB, "GitHub"),
]